PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;


DROP TABLE IF EXISTS "User";

CREATE TABLE User(
	id INTEGER PRIMARY KEY ASC,
	name INTEGER DEFAULT 0 NOT NUll, 		
	age INTEGER NOT NULL
);
INSERT INTO "User" VALUES(null, "John", 18);

COMMIT;
